### ISSUE TITLE
[WEB] GLOBAL New guidelines

### ISSUE THREAD

**Issue by netzulo** [netzulo/qadmin#9]
# TODOs

+ [ ] bootstrap from angular4
+ [ ] logger on client side
+ [ ] logger on server side
+ [ ] page /index , /
+ [ ] page /login
+ [ ] page /dashboard ( *must load menus and main info from API, using token+user_id* )
+ [ ] page /logout
+ [ ] page /404
+ [ ] page /500

+ [ ] **mainmenu** component
  + [ ] **logout** component ( *just button what calls /logout* )
+ [ ] **login** component ( *form with name, pass and button* )

+ [ ] define environment vars , **log_level**
+ [ ] define environment vars , **api_url**
+ [ ] define environment vars , **api_url_log**
